// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJ5Pr_xey9gLwNcMiAS9swPoRSzt4fG-E',
    appId: '1:443896343343:android:7422ef2b86df3703dd0fda',
    messagingSenderId: '443896343343',
    projectId: 'social-game-tracker',
    storageBucket: 'social-game-tracker.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0SWLz_kl13txTN-wwjQ1q6clog2Qx-5s',
    appId: '1:443896343343:web:21c7690ed01a950fdd0fda',
    messagingSenderId: '443896343343',
    projectId: 'social-game-tracker',
    authDomain: 'social-game-tracker.firebaseapp.com',
    storageBucket: 'social-game-tracker.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClGtgkPTenFdNrz6eTQr7Wf_8L1KhVHEE',
    appId: '1:443896343343:ios:8e58fc738f16d5e9dd0fda',
    messagingSenderId: '443896343343',
    projectId: 'social-game-tracker',
    storageBucket: 'social-game-tracker.firebasestorage.app',
    iosBundleId: 'com.example.socialGameTracker',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClGtgkPTenFdNrz6eTQr7Wf_8L1KhVHEE',
    appId: '1:443896343343:ios:8e58fc738f16d5e9dd0fda',
    messagingSenderId: '443896343343',
    projectId: 'social-game-tracker',
    storageBucket: 'social-game-tracker.firebasestorage.app',
    iosBundleId: 'com.example.socialGameTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0SWLz_kl13txTN-wwjQ1q6clog2Qx-5s',
    appId: '1:443896343343:web:f6c542cc11726356dd0fda',
    messagingSenderId: '443896343343',
    projectId: 'social-game-tracker',
    authDomain: 'social-game-tracker.firebaseapp.com',
    storageBucket: 'social-game-tracker.firebasestorage.app',
  );

}